sktime/pytorch-forecasting

README.md, codecov.yml, docs/requirements.txt, docs/source/getting-started.rst, docs/source/index.rst
Merge only when package shows up here: https://anaconda.org/search?q=pytorch-forecasting
=> Add conda to installation instructions

pytorch_forecasting/models/base_model.py
Working with this package has been a pleasure!
The only major snag I've had so far is selecting a sensible LR, I did not realise that the optimiser was ranger, this might have helped me a bit.
=> Add the optimizer options and default to BaseModel doc string

pytorch_forecasting/models/base_model.py
- A in order to stay within a reasonable learning rate range, this MR makes min_lr argument of ReduceLROnPlateau configurable
=> Parameterize the minimum LR that ReduceLROnPlateau can reduce to

.github/workflows/code_quality.yml, .github/workflows/test.yml
Attempt to make all tests run even if branch is in fork
=> Run actions based on master and in master

pytorch_forecasting/models/deepar/__init__.py
I think this might resolve https://github.com/jdb78/pytorch-forecasting/issues/182#issue-753749841
=> DeepAR correctly calculates target position

examples/ar.py
- Actually uses the DeepAR model now with minimal changes to the old version of ar.py
=> Updated example ar.py

CHANGELOG.md, pytorch_forecasting/data/encoders.py, pytorch_forecasting/data/timeseries.py, pytorch_forecasting/metrics.py, pytorch_forecasting/utils.py, tests/test_data.py
=> Check for non-finites in data

CHANGELOG.md, pytorch_forecasting/data/timeseries.py, pytorch_forecasting/models/base_model.py
=> Replace set with dict.fromkeys for reproducibility

.github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.md, pytorch_forecasting/metrics.py, pytorch_forecasting/models/temporal_fusion_transformer/tuning.py, tests/test_models/conftest.py, tests/test_models/test_deepar.py, tests/test_models/test_temporal_fusion_transformer.py
=> Avoid inf losses for Beta distribution

docs/source/models.rst
Fixes a verb in the documentation.
=> Fix marry vs merry

examples/ar.py, poetry.lock, pyproject.toml, pytorch_forecasting/models/temporal_fusion_transformer/tuning.py, pytorch_forecasting/utils.py, tests/test_models/test_deepar.py, tests/test_models/test_nbeats.py, tests/test_models/test_temporal_fusion_transformer.py
=> Upgrade AR example and torch dependency

CHANGELOG.md, pytorch_forecasting/models/base_model.py, tests/test_models/conftest.py
=> Fix multi-length, multi-length targets and add regression test

CHANGELOG.md, pytorch_forecasting/models/base_model.py
=> Fix missing output transformation

CHANGELOG.md, pytorch_forecasting/data/timeseries.py, tests/test_data.py
=> Fix mutable dataframe

CHANGELOG.md, pytorch_forecasting/models/nbeats/__init__.py
=> Fix plot interpretability of NBeats

CHANGELOG.md, pytorch_forecasting/data/encoders.py, pytorch_forecasting/data/timeseries.py, tests/test_data.py
=> Allow adding categories to NaNLabelEncoder

CHANGELOG.md, pytorch_forecasting/models/nbeats/__init__.py, pytorch_forecasting/models/temporal_fusion_transformer/__init__.py
=> Fix memory leak

pytorch_forecasting/metrics.py
=> Fix description of SMAPE and MAPE

CHANGELOG.md, poetry.lock, pyproject.toml, pytorch_forecasting/models/base_model.py
=> Fix gpu checkpoint loading

CHANGELOG.md, pytorch_forecasting/models/base_model.py
=> Autonotebook tqdm change

pytorch_forecasting/data/encoders.py
=> fix typo in np.percentile call

CHANGELOG.md, pytorch_forecasting/metrics.py, pytorch_forecasting/models/base_model.py, pytorch_forecasting/utils.py, tests/test_models/test_temporal_fusion_transformer.py
Fixes issues when data is on different devices
=> Fix conflicting devices

CHANGELOG.md, pytorch_forecasting/models/base_model.py
=> Ensure output can always be concatenated

CHANGELOG.md, pytorch_forecasting/data/timeseries.py, pytorch_forecasting/models/base_model.py
=> Allow lists for multiple losses and normalizers

CHANGELOG.md, docs/source/conf.py, docs/source/index.rst, poetry.lock, pyproject.toml, pytorch_forecasting/data/encoders.py, tests/test_models/conftest.py
=> Ensure tests execute and bad normalization is flagged

.github/workflows/automerge.yml, .github/workflows/lint-comment.yml, .github/workflows/lint.yml
This PR fixes workflow issues with github actions
=> Update github actions workflows

CHANGELOG.md, pytorch_forecasting/models/base_model.py
=> Name log after target name instead of target number

pytorch_forecasting/models/nn/embeddings.py
=> fix infinite loop in TimeDistributedEmbeddingBag

pytorch_forecasting/metrics.py
What confused me a bit is the formula for Quantile loss. The actual implemented method uses the correct formula, only the one in the documentation is wrong, so I fixed it.
=> Fixed some typos.

.pre-commit-config.yaml, CHANGELOG.md, README.md, docs/source/getting-started.rst, examples/ar.py, examples/nbeats.py, examples/stallion.py, pytest.ini, pytorch_forecasting/metrics.py, pytorch_forecasting/models/base_model.py, pytorch_forecasting/models/deepar/__init__.py, pytorch_forecasting/models/nbeats/__init__.py, pytorch_forecasting/models/rnn/__init__.py, pytorch_forecasting/models/temporal_fusion_transformer/sub_modules.py, pytorch_forecasting/models/temporal_fusion_transformer/tuning.py, tests/conftest.py, tests/test_models/conftest.py, tests/test_models/test_baseline.py, tests/test_models/test_deepar.py, tests/test_models/test_mlp.py, tests/test_models/test_nbeats.py, tests/test_models/test_rnn_model.py, tests/test_models/test_temporal_fusion_transformer.py
This PR enables using torchmetrics with models.
=> Automatically convert torchmetrics

.github/workflows/autoapprove.yml, tests/test_models/test_mlp.py, tests/test_models/test_temporal_fusion_transformer.py
=> Switch to native dependabot merge and approve

pytorch_forecasting/optim.py
Fixes https://github.com/jdb78/pytorch-forecasting/issues/793
=> Fix Ranger serialization/deserialization

CHANGELOG.md, pyproject.toml
This PR fixes installs via github
=> Update poetry requirements for pip install github

docs/source/getting-started.rst, docs/source/index.rst, docs/source/tutorials/stallion.ipynb, examples/ar.py, pytorch_forecasting/metrics.py, pytorch_forecasting/models/base_model.py
Fixed some typos that occurred throughout the codebase. 
- [X ] Linked issues (if existing)
- [X ] Amended changelog for large changes (and added myself there as contributor)
- [X ] Added/modified tests
- [X ] Used pre-commit hooks when committing to ensure that code is compliant with hooks. Install hooks with `pre-commit install`.
=> fixed typos

CHANGELOG.md, pytorch_forecasting/models/base_model.py
=> lrs typo fix

pytorch_forecasting/models/temporal_fusion_transformer/__init__.py
=> Fix issue with variable being used before defined in TFT interpretation

pytorch_forecasting/data/encoders.py
=> Fix centering

pytorch_forecasting/metrics/quantile.py
Great work on Pytorch Forecasting!
Spotted a small typo.
=> Spotted a typo.

docs/source/tutorials/ar.ipynb
Fix tiny api bugs and different devices calculation bug mentioned at #1352
=> fix api bugs and different devices calculation bug

.pre-commit-config.yaml, pytorch_forecasting/data/timeseries.py
1. updates all the `pre-commit` hooks to their latest versions using `pre-commit autoupdate`
2. runs all hooks on all files using `pre-commit run --all-files`
=> [MNT] Update pre commit hooks and run all

examples/ar.py, examples/nbeats.py, examples/stallion.py, pytorch_forecasting/data/encoders.py, pytorch_forecasting/data/samplers.py, pytorch_forecasting/metrics/base_metrics.py, pytorch_forecasting/metrics/point.py, pytorch_forecasting/metrics/quantile.py, pytorch_forecasting/models/base_model.py, pytorch_forecasting/models/deepar/__init__.py, pytorch_forecasting/models/nhits/__init__.py, pytorch_forecasting/models/nn/__init__.py, pytorch_forecasting/models/temporal_fusion_transformer/__init__.py, pytorch_forecasting/models/temporal_fusion_transformer/sub_modules.py, tests/test_data/test_timeseries.py, tests/test_metrics.py, tests/test_models/test_deepar.py, tests/test_models/test_mlp.py, tests/test_models/test_nn/test_embeddings.py, tests/test_models/test_rnn_model.py, tests/test_models/test_temporal_fusion_transformer.py
Removes all unused imports in the library.
=> [MNT] remove unused imports

pytorch_forecasting/metrics/distributions.py
This PR collects various code formatting improvements.
=>  [DOC] various code formatting improvements

.github/workflows/pypi_release.yml
Updates the python version in release workflow to 3.11
=> [MNT] update python version in release workflow to 3.11

CHANGELOG.md, pyproject.toml, pytorch_forecasting/__init__.py
Release PR for 1.1.0
* version number bump
* changelog
=> Release 1.1.0

.github/workflows/test.yml
=> [MNT] updates the actions in the doc build CI

.readthedocs.yml, pyproject.toml
Fixes `readthedocs.yml`, closes #1675
=> [MNT] fixes to `readthedocs.yml`

pytorch_forecasting/data/encoders.py, pytorch_forecasting/metrics/base_metrics.py, pytorch_forecasting/models/base_model.py, pytorch_forecasting/models/deepar/__init__.py, pytorch_forecasting/models/rnn/__init__.py
This PR fixes list related linting failures C416 and C419, instances of unnecessary comprehensions.
=> [MNT] `ruff` - fix list related linting failures C416 and C419

CHANGELOG.md
=> [DOC] typo fixes in changelog

CHANGELOG.md, pyproject.toml, pytorch_forecasting/__init__.py
Release PR for 1.2.0
* version number bump
* changelog
Fixes #1707 as this contains the `numpy 2` patch.
=> Release 1.2.0

pytorch_forecasting/data/timeseries.py
This PR fix the spelling error of holding
- [√] Linked issues (if existing)
- [√] Amended changelog for large changes (and added myself there as contributor)
- [√] Added/modified tests
- [√] Used pre-commit hooks when committing to ensure that code is compliant with hooks. Install hooks with `pre-commit install`.
=> Fix the spelling error of holding

pytorch_forecasting/models/tide/__init__.py, pytorch_forecasting/models/tide/sub_modules.py
This PR lints the tide model files.
=> [ENH] linting tide model

pyproject.toml, pytorch_forecasting/utils/_maint/_show_versions.py
Some minor fixes in documentation
=> [DOC] minor fixes in documentation

docs/source/models.rst, pytorch_forecasting/__init__.py, pytorch_forecasting/models/__init__.py, pytorch_forecasting/models/tide/_tide.py, pytorch_forecasting/models/tide/sub_modules.py
=> [DOC] improve and add `tide` model to docs

CHANGELOG.md
fixes a minor typo in the changelog
=> [DOC] fix minor typo in changelog
