sktime/pytorch-forecasting

pytorch_forecasting/data/timeseries.py
pytorch_forecasting/models/temporal_fusion_transformer/sub_modules.py

Fixing the naming of fully connected network in the GLU submodule when initializing its weights. The name is fc, but the initializing method was searching for fc2 which doesnt exist in that sub module.

Fixing typo in GLU initialization

---

pytorch_forecasting/models/temporal_fusion_transformer/__init__.py
pytorch_forecasting/models/temporal_fusion_transformer/sub_modules.py

If different encoder lengths are fed to TFT, the attention on the time steps that it is predicting for varies. It is better to not attend to itself so that the attention is solely on the encoder

Do not attend to current timestep in TFT

---

pytorch_forecasting/models/temporal_fusion_transformer/__init__.py

There were two forward passes for the decoder LSTM, which waste (actually a lot) of CPU/GPU cycles.

Removed duplicate forward pass for decoder LSTM

---

pytorch_forecasting/models/base_model.py

- Fixes issue bug when trying to make predictions with model / data that are not on the same device
https://stackoverflow.com/questions/59560043/what-is-the-difference-between-model-todevice-and-model-model-todevice

BaseModel.predict() properly moves inputs to device

---

pytorch_forecasting/data/encoders.py

I think you forgot to add an underscore to self.norm_ atribute of the GroupEncoder.

Fixed self.norm_ in GroupEncoder in fit method

---

pytorch_forecasting/data/timeseries.py
tests/test_data.py

Enable longer subsequences for min_prediction_idx that were previously wrongfully excluded

---

pytorch_forecasting/models/temporal_fusion_transformer/tuning.py
tests/test_models/test_temporal_fusion_transformer.py

This PR fixes #299 
Overwriting default kwargs is sometimes useful, e.g. disabling logging or setting `progress_bar_refresh_rate>=20` on colab.

Make tuning trainer kwargs overwritable

---

CHANGELOG.md
pytorch_forecasting/data/timeseries.py
pytorch_forecasting/models/base_model.py
tests/test_models/test_temporal_fusion_transformer.py

- Handling multi-target prediction case with return_x=True.
- Concatenation of multi-target prediction output by target instead of batch. (little bug fix)

Handling `return_x=True` in case of multi-target prediction

---

.github/workflows/automerge.yml
docs/source/_static/custom.css
docs/source/index.rst

This PR adds back a link to github on the docs

Add back link to github to docs

---

CHANGELOG.md
pytorch_forecasting/metrics.py

Fix metrics

---

CHANGELOG.md
pytorch_forecasting/models/temporal_fusion_transformer/__init__.py
tests/test_models/conftest.py

This PR fixes an issue when the passed loss function is not correctly modified for the TFT.

Fix initialization of tft with correct order of arguments

---

pytorch_forecasting/models/base_model.py

This PR fixes the typo ```pot_prediction -> plot_prediction``` present in the ```log_prediction()``` function in the definition of the class ```BaseModel```.

Fixed typo in BaseModel doc string

---

CHANGELOG.md
pytorch_forecasting/models/base_model.py
pytorch_forecasting/models/mlp/__init__.py
tests/test_models/test_mlp.py

Optimizer can be initialized by passing string, class or function + fixing transformation for MLP

Make optimizer initialization flexible

---

CHANGELOG.md
pytorch_forecasting/models/base_model.py
pytorch_forecasting/models/baseline.py
tests/test_models/test_baseline.py

Allow multi-target prediction with Baseline model

---

CHANGELOG.md
pytorch_forecasting/models/temporal_fusion_transformer/tuning.py

Add possibility to change pruner for `optimize_hyperparameters` in `TFT` according to #589 

Added pruner option to TFT optimize_hyperparameters-method

---

docs/source/getting-started.rst

Typo in argument of TimeSeriesDataSet. I was studying pytorch forecasting with getting-started documents, and I found some little typo.. 

Typo in argument of TimeSeriesDataSet

---

pytorch_forecasting/data/encoders.py
tests/test_data.py

- add fitted_ attribute to MultiNormalizer when fit is called

---

.github/workflows/pypi_release.yml
.github/workflows/test.yml
.readthedocs.yml
CHANGELOG.md
poetry.lock
pyproject.toml
pytorch_forecasting/data/encoders.py
pytorch_forecasting/data/timeseries.py
pytorch_forecasting/models/base_model.py
pytorch_forecasting/models/nbeats/sub_modules.py

Maintenance issues

---

CHANGELOG.md
pytorch_forecasting/models/deepar/__init__.py
pytorch_forecasting/models/rnn/__init__.py

This PR fixed an issue about inattention mutation with `x_cont` that caused original data changed.
The mutation happened here:
```python
input_vector[..., self.target_positions] = torch.roll(
input_vector[..., self.target_positions], shifts=1, dims=1
)
```
It caused `x_cont` changed. And the changes keep exists from `encode` to `decode`. So, the shift happen twice. 

Fix inattention mutation to `x_cont`.

---

pytorch_forecasting/data/encoders.py

This PR addresses #635. As the issue author mentioned, the [current](https://github.com/jdb78/pytorch-forecasting/blob/master/pytorch_forecasting/data/encoders.py#L117) `np.isin` condition doesn't work right and yields to raising UserWarning all the time, at least for `y` being `pandas.Series` object (in my testing).
Maybe this fix is a bit clanky in terms of performance, so would be glad to hear any suggestions!

Fix condition for UserWarning (issue #635)

---

poetry.lock
pytorch_forecasting/models/base_model.py
tests/test_models/test_mlp.py

fixed accessing model.val_dataloader to model.trainer.val_dataloader

---

pytorch_forecasting/models/base_model.py

This PR allows the `weight_decay` and `optimizer_params` hparams to be taken into account by all optimizers. Currently, adam ignores both, and adamw and ranger ignore `optimizer_params`.
Fixes #706 

Make all optimizers use `weight_decay` and `optimizer_params`

---

pytorch_forecasting/data/encoders.py
tests/test_data.py

Addresses #574 by avoiding type promotion from float32 -> float64 during `TorchNormalizer` transformations.
- ~[] Amended changelog for large changes (and added myself there as contributor)~ --> just a bugfix here
Make sure to have fun coding! :heavy_check_mark:

Ensure `TorchNormalizer` transformation output type matches input type

---

pytorch_forecasting/data/timeseries.py

This PR fixes this warning given by PyTorch in the collate function of the timeseries data script:
```
../anaconda3/envs/env/lib/python3.8/site-packages/pytorch_forecasting/data/timeseries.py:1654:
UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow.
Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor.
(Triggered internally at  ../torch/csrc/utils/tensor_new.cpp:201.)
--> scale = torch.tensor([batch[0]["target_scale"][idx] for batch in batches], dtype=torch.float)
```
The list of numpy arrays is casted into a single numpy array before being casted to a torch tensor.
Notice that there is probably a small bug in the `log_gradient_flow` method of the `BaseModel`, for which some tests don't pass. More …

Fix warning in timeseries collate function

---

pytorch_forecasting/data/timeseries.py

Fixes another warning when converting from numpy to torch in collate function.

Fix another numpy to torch conversion warning

---

.github/workflows/automerge.yml
CHANGELOG.md
pytorch_forecasting/models/basic_rnn/__init__.py
pytorch_forecasting/models/deepar/__init__.py
pytorch_forecasting/models/mlp/__init__.py
pytorch_forecasting/models/nn/embeddings.py
pytorch_forecasting/models/rnn/__init__.py
pytorch_forecasting/models/temporal_fusion_transformer/__init__.py
tests/test_models/test_nn/test_embeddings.py

This PR makes the MultiEmbedding a bit more flexible and adds additional properties for convenience to deduce output and input sizes.

More flexible multiembedding

---

CHANGELOG.md
pytorch_forecasting/metrics.py
pytorch_forecasting/models/base_model.py
pytorch_forecasting/models/temporal_fusion_transformer/__init__.py
pytorch_forecasting/utils.py
tests/test_models/test_temporal_fusion_transformer.py

This PR fixes an issue with attention calculation accross many samples and predict(mode="raw") failing.

Fix attention concat

---

CHANGELOG.md
docs/requirements.txt
poetry.lock
pytorch_forecasting/data/encoders.py
pytorch_forecasting/metrics.py
pytorch_forecasting/models/base_model.py
pytorch_forecasting/models/temporal_fusion_transformer/__init__.py

This PR fixes issues with training on GPU and MultiLoss

Fixes for GPU and MultiLoss

---

pytorch_forecasting/data/encoders.py
tests/test_data/test_encoders.py

This PR aims at fixing issue #998 by making changes in method `_set_parameters` of `TorchNormalizer`.
The following assertion was added in `tests/test_data/test_encoders.py`:
```
y = np.array([1, 2, 3], dtype=np.float32)
assert TorchNormalizer(method="identity").fit(y).get_parameters().dtype == torch.float32
```
Before the changes made, this assertion would fail (the dtype would be `torch.float64` due to numpy default dtype `numpy.float64`) which then would potentially cause dtype issues (e.g., in method `decode` of DeepAR and more specifically `decode_autoregressive`: the first lagged value was of dtype torch.float32 -true observed value- while the subsequent values -predictions- were of dtype torch.float64).
Not 100% sure the problem should not have been fixed on DeepAR side but note …

bugfix: dtype inconsistency in TorchNormalizer with method='identity'

---

.github/workflows/pypi_release.yml
.github/workflows/test.yml
CHANGELOG.md
README.md
docs/source/_static/custom.css
docs/source/conf.py
docs/source/getting-started.rst
docs/source/index.rst
docs/source/tutorials/nhits.ipynb
poetry.lock
pyproject.toml
pytorch_forecasting/data/encoders.py
pytorch_forecasting/data/examples.py
pytorch_forecasting/metrics/base_metrics.py
pytorch_forecasting/metrics/distributions.py
pytorch_forecasting/metrics/point.py
tests/test_models/test_nhits.py
tests/test_models/test_temporal_fusion_transformer.py

This PR updates the poetry install method - fixing the CI.

Update new poetry install method

---

pytorch_forecasting/data/encoders.py

This PR fixes the dtype check in `is_numeric`. Currently, it will always evaluate to `pandas.core.series.Series` and never a categorical type as we are checking the `type` of the series that is passed in. This modifies to check if the dtype is categorical, which I think is the desired usage.

Fix dtype check

---

CHANGELOG.md
docs/source/_static/custom.css
pytorch_forecasting/data/encoders.py
tests/test_data/test_encoders.py

Fix robust scaler - move to quantiles instead of kthvalue

---

pytorch_forecasting/models/base_model.py

This PR fixes an error when handing over `trainer_kwargs` to `predict_dependency()`, as in the following example:
```
model.predict_dependency(ds, "feature", np.linspace(0, 30, 30), mode="dataframe",  trainer_kwargs={ "accelerator": "cpu"})
```
Overwriting `trainer_kwargs` might be necessary when using a model trained on GPU. The issue comes from the `kwargs` dict handed over to `predict_dependency()` being overwritten in `predict()`, which will cause it to contain a `PredictCallback(return_index=True, ...)` in the `kwargs["trainer_kwargs"]["callbacks"]` list, even in the second iteration where `return_index` should be `False`, causing a subsequent error 
```
File ~/Library/Caches/pypoetry/virtualenvs/discovery-lab-rTrwb4a5-py3.10/lib/python3.10/site-packages/pytorch_forecasting/models/bas …
```

Fix error when handing over trainer_kwargs to predict_depency()

---

pytorch_forecasting/data/timeseries.py

`None` is already allowed in the docs and code - let's put it in the Python typing please

Add None as valid type for target_normalizer

---

pytorch_forecasting/data/timeseries.py

This PR fixes RuntimeError during calculation of weighted MultiHorizonMetric loss due to losses and weights shape mismatch.
```
training_dataset = TimeSeriesDataSet(
dataset.loc[dataset["date"] <= cutoff_],
time_idx="time_idx",
target="target",
weight="weight",
group_ids=["group_id_1", "group_id_2", "group_id_3"],
min_encoder_length=max_encoder_length // 2,
max_encoder_length=max_encoder_length,
min_prediction_length=1,
max_prediction_length=max_prediction_length,
static_categoricals=static_categoricals,
time_varying_known_reals=time_varying_known_reals,
time_varying_known_categoricals=time_varying_known_categoricals,
time_varying_unknown_reals=time_varying_unknown_reals,
target_normalizer=target_normalizer,
categorical_encoders=categorical_encoders,
scalers=scalers, …
```

Bugfix, weights shape during length randomization

---

README.md

It seems that the workflow was renamed, so the badge is wrong:
- actual -> ![](https://github.com/jdb78/pytorch-forecasting/actions/workflows/code_quality.yml/badge.svg?branch=master)
- fixed -> ![](https://github.com/jdb78/pytorch-forecasting/actions/workflows/lint.yml/badge.svg?event=push)
cc: @jdb78

readme: fix linter badge

---

.github/workflows/test.yml
docs/requirements.txt
docs/source/tutorials/stallion.ipynb
pytorch_forecasting/models/temporal_fusion_transformer/tuning.py

This PR resolved to build docs and so unblocked the long queue with pending PRs
`TypeError: Cannot create a consistent method resolution order (MRO) for bases Callback, PyTorchLightningPruningCallback`
see the fixed - :green_circle: on forked CI https://github.com/Lightning-Sandbox/pytorch-forecasting/pull/1
cc: @jdb78

resolving method resolution order (MRO) to fix docs build

---

.github/workflows/test.yml
build_tools/run_examples.sh
docs/source/tutorials/ar.ipynb
docs/source/tutorials/building.ipynb
docs/source/tutorials/deepar.ipynb
docs/source/tutorials/nhits.ipynb
docs/source/tutorials/stallion.ipynb
pyproject.toml
pytorch_forecasting/__init__.py

fix https://github.com/jdb78/pytorch-forecasting/issues/1539
Removed `os.chdir("../../..")` in notebooks.
This PR should be merged after https://github.com/jdb78/pytorch-forecasting/pull/1599

[BUG] Fix pyproject package structure and failures in tutorial notebooks

---

tests/test_models/test_temporal_fusion_transformer.py

This PR skips tests involved in the failures on windows listed in #1623 until the underlying issues are resolved, see #1632 and #1632

[MNT] skip tests involved in windows failures until resolved

---

.github/workflows/test.yml

This PR extends the CI matrix to `windows-latest`, for testing windows OS compatibility.

[MNT] CI matrix extended to `windows-latest`

---

pyproject.toml

This Pr isolates `cpflows` to its soft dependency set again - I think it was already a soft dependency before we started to rework `pyproject`, somehow it ended up in `dev`?
This PR restores its original status as a soft dependency, as part of `mqf2`.

[MNT] isolate `cpflows` to its soft dependency set

---

.github/workflows/test.yml
tests/test_models/test_nhits.py
tests/test_models/test_temporal_fusion_transformer.py

This adds test runs without soft dependencies.
The run covers currently removal of the two extant soft dependency sets, `graph` and `mqf2`. This tests isolation in the extents of test coverage, and also isolation of the tests themselves requiring these.
The setup can be extended in the future to further soft dependency sets, testing that the code functions in their absence.

[MNT] CI runs without soft dependencies

---

codecov.yml

The `codecov` patch job, i.e., "how many lines of the diff are covered", can cause CI failures currently - these are misleading in particular if the code is maintenance or config code and itself not covered due to reasonable circumstances.
To avoid random failures in such cases, the patch coverage is turned to be informational. The total coverage condition, i.e., that total rpeository coverage should not drop too much through a PR, is not changed.

[MNT] make `codecov` patch coverage informational

---

pyproject.toml

This renames the `pytorch-optimizer` dep to `pytorch_optimizer` and raise upper bound to `<4`
The package seems to have been renamed to `pytorch_optimizer` on pypi?

[MNT] rename `pytorch-optimizer` dep to `pytorch_optimizer` and raise upper bound to `<4`

---

.github/workflows/test.yml
pyproject.toml

Cleans up dependency management without making changes to existing dep sets.
* create new dep set `all_extras` containing all used soft dependencies
* reorder dep sets in `pyproject.toml` and and comments about their usage
* remove unused `graph` dep set from installations in CI - the contained `networkx` package is never imported within the code base

[MNT] clean up and comment dep sets in `pyproject.toml`, remove unused `graph` dep set from CI

---

.github/workflows/test.yml
pyproject.toml
pytorch_forecasting/data/timeseries.py
pytorch_forecasting/models/base_model.py
pytorch_forecasting/models/nbeats/__init__.py
pytorch_forecasting/models/nhits/__init__.py
pytorch_forecasting/models/temporal_fusion_transformer/__init__.py
pytorch_forecasting/utils/_dependencies.py
tests/test_models/test_nbeats.py
tests/test_models/test_nhits.py
tests/test_models/test_temporal_fusion_transformer.py

Isolates `matplotlib` as soft dependency in a new soft dep set `all_extras`. https://github.com/jdb78/pytorch-forecasting/issues/1616
The imports happen in `plot_sth` methods throughout the code base, some attached to classes, some not.
This allows to use `pytorch-forecasting` without plotting or graphical logging, or use a different plotting backend manually.
Isolation strategy:
* where the purpose of the function is creating a plot or nothing else, absence of `matplotlib` raises an exception
* where `matplotlib` is additional or part of the logic, absence of `matplotlib` causes the specific parts to be skipped. Example: `log_gradient_flow` - this is crucial, as raising an exception would prevent the models from running.

[MNT] isolate `matplotlib` as soft dependency

---

.github/workflows/test.yml
pyproject.toml
pytorch_forecasting/models/base_model.py

Isolates `pytorch-optimizer` as soft dependency in a new soft dep set `all_extras`. https://github.com/jdb78/pytorch-forecasting/issues/1616
The imports happen only in `BaseModel`, when resolving aliases for `optimizer`.
Isolation consists of two steps:
* replacing resolution of the alias with a request to install the package, and removing from resolution scope if not installed
* replacing the default optimizer `"ranger"` with `"adam"` if `pytorch-optimizer` is not installed (left at `"ranger"` if installed)
Deprecation messages and actions are added, to changne the default to `"adam"` from 1.2.0, in order to minimize the number of dependencies in default parameter settings

[MNT] isolate `pytorch-optimizer` as soft dependency

---

.github/workflows/pypi_release.yml

This PR ensures that the release workflow is triggered only on GitHub release.
Currently, it seems the release is triggered on every push to `master` - though it has thankfully failed for the past merges.

[MNT] pypi release only on GH release

---

.github/workflows/pypi_release.yml

Makes changes and improvements to the release workflow:
* using python 3.11
* based on `pip` and not `poetry`
* gating the actual push to `pypi` behind a full run of the nosoftdeps tests to avoid pushing a failing version

[MNT] improved release workflow

---

pytorch_forecasting/__init__.py
pytorch_forecasting/utils/_maint/_show_versions.py
pytorch_forecasting/utils/_maint/tests/__init__.py
pytorch_forecasting/utils/_maint/tests/test_show_versions.py
tests/test_utils/test_show_versions.py

Adds a `show_versions` utility for users to easily share version information in bug reports or questions.
Adapted from `sktime`, which in turn is an evolution of the `sklearn` utility of the same name.

[MNT] `show_versions` utility

---

docs/source/tutorials/stallion.ipynb
examples/ar.py
examples/nbeats.py
examples/stallion.py
pytorch_forecasting/data/timeseries.py

Cleaned up the offending items so `pre-commit` passes on main.
Fixes https://github.com/sktime/pytorch-forecasting/issues/1695
This quick fix sorts out the files causing `pre-commit` to fail on `main`, so it can run again.

[MNT] fix `pre-commit` failures on `main`

---

pyproject.toml

This PR adds the correct dependency for `black` jupyter instead of `extras` as it doesn't have that.

[MNT]`black` doesn't have `extras` dependency

---

pytorch_forecasting/models/base_model.py
pytorch_forecasting/models/nbeats/__init__.py
pytorch_forecasting/models/nhits/__init__.py
pytorch_forecasting/models/temporal_fusion_transformer/__init__.py

This PR fixes #1256.
At present, the `AttributeError` is raised (and the script exits) if the logger used does not have the `add_figure` method.
This fix adds a simple check prior to calling `add_figure`.

[BUG] fix `AttributeError: 'ExperimentWriter' object has no attribute 'add_figure'`

---

CODEOWNERS

This PR adds a CODEOWNERS file, which ensures that maintainers are pinged when a PR is opened.
I have included from among `sktime` and `pytorch-forecasting` maintainers those that have contributed to `pytorch-forecasting` more than occasionally - please let me know if you prefer not to be on this list.

[MNT] CODEOWNERS file

---

pytorch_forecasting/data/timeseries.py

Documentation PR.
Clarifies use of `predict_mode` for [TimeSeriesDataSet](https://pytorch-forecasting.readthedocs.io/en/stable/api/pytorch_forecasting.data.timeseries.TimeSeriesDataSet.html#).

[DOC] Updated documentation on `TimeSeriesDataSet.predict_mode`

---

LICENSE

This PR extends the copyright to the present.
The package remains, of course, permissive license.
The impact is a required authorship attribution to "pytorch-forecasting developers" in any copied code.

[ENH] extend package author attribution requirement in license to present

---

pytorch_forecasting/models/tide/__init__.py
pytorch_forecasting/models/tide/sub_modules.py

Fixes: #1337 
This PR implements end to end tide model interface in pytorch-forecasting. Also tested model on different datasets such as univariate airline data from sktime.

Tide model interface in pytorch-forecasting.

---

pytorch_forecasting/models/tide/__init__.py
pytorch_forecasting/models/tide/_tide.py

Follows https://github.com/sktime/pytorch-forecasting/pull/1743, adds exports and linting.

[ENH] move tide model - part 2

---

pytorch_forecasting/data/timeseries.py

This PR carries out a clean-up refactor of `TimeSeriesDataSet`. No changes are made to the logic.
This is in preparation for major work items impacting the logic, e.g., removal of the `pandas` coupling (see https://github.com/sktime/pytorch-forecasting/issues/1685), or a 2.0 rework (see https://github.com/sktime/pytorch-forecasting/issues/1736).
In general, a clean state would make these easier.
Work carried out:
* clear, and complete docstrings, in numpydoc format
* separating logic, e.g., for parameter checking, data formatting, default handling
* reducing cognitive complexity and max indentations, addressing "code smells"
* linting

[ENH] clean-up refactor of `TimeSeriesDataSet`

---

.github/workflows/pypi_release.yml

Moves the release to trusted publishers.
All secrets have been removed from the repo.

[MNT] move release to trusted publishers

---

.github/dependabot.yml

Standardizes `dependabot.yml` to be the same as for the other `sktime` maintained packages.

[MNT] standardize `dependabot.yml`

---

pytorch_forecasting/data/timeseries.py

As it was introduced in [pep 585](https://peps.python.org/pep-0585/) we can use standard collections as type hints.
part of #1817

[ENH] Add Typehints to `TimeSeriesDataSet` to align with pep 585

---

pytorch_forecasting/utils/_dependencies/_safe_import.py
pytorch_forecasting/utils/_dependencies/tests/__init__.py
pytorch_forecasting/utils/_dependencies/tests/test_safe_import.py
tests/test_utils/test_safe_import.py

The issue was spotted in sktime via https://github.com/sktime/sktime/pull/8061
Updated the implementation and copied the unit tests to ensure that it works with pytorch-forecasting.
closes https://github.com/sktime/pytorch-forecasting/issues/1815

[ENH] Allow multiple instances from multiple mock classes in `_safe_import`

---

pytorch_forecasting/data/data_module.py
tests/test_data/test_data_module.py

This PR solves the bug in `data_module` where the `static_categorical_features` and `static_continuous_features` were not correctly calculated in `__getitem__` of nested class

[BUG] EXPERIMENTAL PR: Solve the bug in `data_module`

---

pytorch_forecasting/data/data_module.py
tests/test_data/test_data_module.py

This PR makes the `data_modulel` dataclass-like
See discussion in #1829

[ENH] EXPERIMENTAL PR: make the `data_module` dataclass-like

---

pytorch_forecasting/models/deepar/_deepar_metadata.py
pytorch_forecasting/models/nbeats/__init__.py
pytorch_forecasting/models/nbeats/_nbeats_metadata.py
pytorch_forecasting/models/tide/_tide_metadata.py
pytorch_forecasting/tests/_conftest.py
pytorch_forecasting/tests/test_all_estimators.py
tests/test_models/test_tide.py

Refactors the test metadata container to include data loader configs which may vary, adds this in a private class method `_get_test_dataloaders_from`. Also refactors the `_integration` method in `TestAllEstimators` accordingly.
Also:
* Adds `NBeats` metadata container for v1 tests.
* Removes the private import from `test_tide`, of `_integration` from `test_all_estimators`

[ENH] refactor test metadata container to include data loader configs

---

pytorch_forecasting/models/mlp/_decodermlp_metadata.py
pytorch_forecasting/models/nbeats/_nbeats_metadata.py
pytorch_forecasting/tests/_conftest.py
pytorch_forecasting/tests/_data_scenarios.py
tests/test_models/conftest.py

This PR moves all test data scenario generation to `tests._data_scenarios`.
It also deduplicates current data scenario code.

[ENH] refactor test data scenario generation to `tests._data_scenarios`

---

pytorch_forecasting/data/encoders.py
pytorch_forecasting/models/temporal_fusion_transformer/tuning.py
tests/test_metrics.py

Fixes https://github.com/sktime/pytorch-forecasting/issues/1901
This PR fixes the issue with 
```python
encoder = EncoderNormalizer(
method='standard',
center=False,
max_length=None,
transformation=None,
method_kwargs={}
)
```
which was returning `scale_` as `mean` of `x` instead its `std`
Temporarily backported lazywhere implementation from `scipy._lib._util.` to avoid import errors in the `statsmodels` with the latest scipy version.

[BUG] Fix issue with `EncodeNormalizer(method='standard', center=False)` for scale value

---

pytorch_forecasting/data/timeseries/_timeseries.py

#648
- Replaced @ property and @lru_cache with @cached_property to fix a self-reference leak: previously, the cache kept strong references to every instance, preventing garbage collection and causing memory growth if many instances were created.
- Improved _construct_index() function to return only essential columns in a consistent format.
Code to check memory leak and fix:
```
"""
Save as profile_timeseries.py
Run with:
mprof run python profile_timeseries.py      # interactive plot after the run
or plain:
python -m memory_profiler profile_timeseries.py
"""
import gc
import os
import time
import tracemalloc
import numpy as np
import pandas as pd
import psutil
from memory_profiler import profile
from pytorch_forecasting import TimeSeriesDataSet
process = psutil.Process(os.getpid())
def …
```

[BUG] fixed memory leak in `TimeSeriesDataset` by using `@cached_property` and clean-up of index construction

---

pytorch_forecasting/data/encoders.py

fixes https://github.com/sktime/pytorch-forecasting/issues/1764
Adding the comments from the Initial PR https://github.com/sktime/pytorch-forecasting/pull/1855 by @fkiraly 
The reason is that `numpy 2` added additional arguments to `__array_wrap__` which was interacting with `torch.Tensor.__array_wrap__` or `pandas.Series.__array_wrap__` that did not have said arguments on earlier versions, in `TorchNormalizer`.
The warning can be avoided by explicit coercion to `torch` prior to mixed usage - avoiding mixed types across packages entirely.
This also makes the coercions more explicit, enabling future refactors where we may want to move to more "clean" type assumptions instead of polymorphic union types.

[ENH] Suppress `__array_wrap__` warning in `numpy 2` for `torch` and `pandas`

---

pytorch_forecasting/data/encoders.py
tests/test_data/test_encoders.py

fixes https://github.com/sktime/pytorch-forecasting/issues/1822
This PR fixes the issue with `plot_prediction_actual_by_variable` where the input `np.ndarray` was being multiplied to `torch.Tensor` in `TorchNormalizer` `__call__`

[BUG] Fix issue with `plot_prediction_actual_by_variable`  unsupported operand type(s) for *: 'numpy.ndarray' and 'Tensor'

---

docs/source/models.rst

fixes https://github.com/sktime/pytorch-forecasting/issues/1881

[DOC] Correct documentation for N-BEATS

---

pytorch_forecasting/models/dlinear/_dlinear_v2.py

Behavior remains the same (in-place initialization)

[ENH] Suppress PyTorch deprecation warning: UserWarning: `nn.init.constant` is now deprecated in favor of `nn.init.constant_`

---

pytorch_forecasting/tests/_base/_fixture_generator.py

The current `BaseFixtureGenerator` is intended to serve as a common base class for generating fixtures in both model and metric test frameworks. However, it still contains model-specific references (e.g., `all_model_pkgs`), which is against its general-purpose design.
This PR refactors the class to remove model-specific terminology and behavior. It introduces more generic naming conventions (e.g., renaming `all_model_pkgs` to `all_pkgs`)
FYI @PranavBhatP

[ENH] Remove references to model from the `BaseFixtureGenerator`

---

pytorch_forecasting/utils/_dependencies/_dependencies.py

Fixed the following bug 
pytorch_forecasting\utils\_dependencies\_dependencies.py:19, in _get_installed_packages_private()
---> 19 package_names = {dist.metadata["Name"] for dist in dists}
TypeError: 'NoneType' object is not subscriptable
Fixes #1925
Added exception handling to the original package_names = {dist.metadata["Name"] for dist in dists}
No
- [-] Added/modified tests

[BUG] fix broken version inspection if package distribution has `None` name

---

tests/test_models/test_temporal_fusion_transformer.py

removes import conditionals for `python 3.6` - 3.6 has been deprecated for years now.

[MNT] remove import conditionals for `python 3.6`

---

pytorch_forecasting/metrics/point.py

There is a missing parenthesis in the documentation of the function MASE.
```
Current: (y_pred - target).abs() /  all_targets[:, :-1] - all_targets[:, 1:]).mean(1)
^
|
v
Correct: (y_pred - target).abs() / (all_targets[:, :-1] - all_targets[:, 1:]).mean(1)
```
NA — Too simple to create an issue, I think.
This commit adds the missing parenthesis.
NA
NA
NA

[DOC] Missing parenthesis in docstring of MASE

---

tests/test_models/test_timexer.py

Adds the test for the output shapes of the forward method of `TimeXer`. The test checks the output contract for the model, which is being implemented in #1936. Currently skipped under `test_timexer.py` due to obvious causes of failure i.e current version of model on main is still not updated to the required output contract.

[ENH] Add missing test for forward output of `TimeXer` as proposed in #1936

---

pytorch_forecasting/models/nbeats/_nbeats_adapter.py
pytorch_forecasting/models/nbeats/_nbeats_pkg.py
pytorch_forecasting/models/nbeats/_nbeatskan_pkg.py

This PR updates the NBeatsAdapter to ensure that both NBeats and NBeatsKAN models return 3D tensors (batch_size, prediction_length, 1) for point predictions, aligning with the expected output format #1975.

Standardize output format of NBeats and NBeatsKAN estimators
